import java.io.BufferedReader;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.time.DayOfWeek;
import java.util.HashMap;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Justin Hovious
 */
public class StaffScheduleFrame extends javax.swing.JFrame {
    private HashMap<String, StaffDB> employees;
    private DefaultTableModel scheduleTableModel;

    /**
     * Creates new form StaffScheduleFrame
     */
    public StaffScheduleFrame() {
        this.employees = new HashMap<>();
        initComponents();
        loadEmployeeData("employeedata.csv");
        populateScheduleTable();
    }

    private void loadEmployeeData(String csvFilePath) {
        try (BufferedReader reader = new BufferedReader(new FileReader(csvFilePath))) {
        String line;
        reader.readLine();

        while ((line = reader.readLine()) != null) {
            String[] fields = line.split(",");
            StaffDB staffDB = new StaffDB(
                fields[0],
                fields[1],
                fields[2],
                fields[3],
                fields[4],
                fields[5],
                Integer.parseInt(fields[6]),
                Integer.parseInt(fields[7]),
                Integer.parseInt(fields[8])
                );
                employees.put(staffDB.getEmployeeId(), staffDB);
            }   
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error reading employee data: " + e.getMessage(),
                    "File Read Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
        
        private void populateScheduleTable() {
            scheduleTableModel = (DefaultTableModel) jTable1.getModel();
            scheduleTableModel.setRowCount(0);
            
            LocalDate today = LocalDate.now();
            LocalDate nextSunday = today.with(TemporalAdjusters.nextOrSame(DayOfWeek.SUNDAY));
            LocalDate nextSaturday = nextSunday.plusDays(6);
            
            DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MM/dd");
            
            String[] headerWithDates = {"Employee",
                nextSunday.format(dateFormatter),
                nextSunday.plusDays(1).format(dateFormatter),
                nextSunday.plusDays(2).format(dateFormatter),
                nextSunday.plusDays(3).format(dateFormatter),
                nextSunday.plusDays(4).format(dateFormatter),
                nextSunday.plusDays(5).format(dateFormatter),
                nextSaturday.format(dateFormatter)
            };
            scheduleTableModel.setColumnIdentifiers(headerWithDates);
            
            //populate schedule for each employee
            for (StaffDB employee : employees.values()) {
                Object[] rowData = new Object[8];
                rowData[0] = employee.getName();
                
                //determine schedule for each day
                for (int i = 0; i < 7; i++) {
                    LocalDate currentDate = nextSunday.plusDays(i);
                    String schedule;
                    
                    if (currentDate.getDayOfWeek() == DayOfWeek.SATURDAY ||
                        currentDate.getDayOfWeek() == DayOfWeek.SUNDAY) {
                        schedule = "OFF";
                    } else {
                        schedule = "9a-5p";
                    }
                    rowData[i + 1] = schedule;
                }
                scheduleTableModel.addRow(rowData);
            }
            
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Staff Schedule");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel1)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffScheduleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
