import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author iamth
 */
public class UserMenuFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form UserMenuFrame1
     */
    
        private Staff staff;
    private HashMap<String, StaffDB> employees;
    private HashMap<Integer,InventoryDB> items;
    private HashMap<Integer,TicketDB> tickets;
    private Inventory item;
    private TicketsMenu ticket;
    private String userID;
    private boolean manager;
    
    
    public UserMenuFrame1() {
                
        employees = null;
        staff = null;
        items = null;
        item = null;
        tickets = null;
        ticket = null;
        userID = null;
        manager = false;
        initComponents();
    }
    
    public UserMenuFrame1(HashMap<String, StaffDB> employeesDB, 
            HashMap<Integer,InventoryDB>itemsDB, Staff staff1,HashMap<Integer,TicketDB> ticketsDB, String id, boolean managerCheck) {
        
        
       
        employees = employeesDB;
        staff = staff1;
        items = itemsDB;
        manager = managerCheck;
        item = new Inventory(employees, items, manager);
        tickets = ticketsDB;
        ticket = new TicketsMenu(tickets, manager);
        userID = id;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TicketsMenuButton = new javax.swing.JButton();
        inventoryMenuButton = new javax.swing.JButton();
        customerMenuButton = new javax.swing.JButton();
        staffMenuButton = new javax.swing.JButton();
        storeInfoButton = new javax.swing.JButton();
        managerMenuButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        purchaseMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setText("User Menu");

        TicketsMenuButton.setText("Tickets Menu");
        TicketsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketsMenuButtonActionPerformed(evt);
            }
        });

        inventoryMenuButton.setText("Inventory Menu");
        inventoryMenuButton.setMaximumSize(new java.awt.Dimension(150, 45));
        inventoryMenuButton.setMinimumSize(new java.awt.Dimension(150, 45));
        inventoryMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryMenuButtonActionPerformed(evt);
            }
        });

        customerMenuButton.setText("Customer Menu");
        customerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuButtonActionPerformed(evt);
            }
        });

        staffMenuButton.setText("Staff Menu");
        staffMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffMenuButtonActionPerformed(evt);
            }
        });

        storeInfoButton.setText("Store Info");
        storeInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeInfoButtonActionPerformed(evt);
            }
        });

        managerMenuButton.setText("Manager Menu");
        managerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerMenuButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        purchaseMenuButton.setBackground(new java.awt.Color(204, 204, 204));
        purchaseMenuButton.setText("Purchase ");
        purchaseMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(purchaseMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(purchaseMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(customerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TicketsMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(storeInfoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inventoryMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(managerMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staffMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel1)))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(managerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storeInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketsMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
                //Gets data from file
                BufferedReader reader = new BufferedReader(new FileReader("ticketdata.csv"));
                ArrayList<String> tableInfo = new ArrayList<>();
                String line;

                while ((line = reader.readLine()) != null){
                    tableInfo.add(line);
                }
                reader.close();
                //Put data in table
                for(String rowInfo : tableInfo){
                    String[] row = rowInfo.split(",");

                    TicketDB ticket = new TicketDB(Integer.valueOf(row[0]), row[1], row[2], row[3], row[4]);
                    tickets.put(Integer.valueOf(row[0]), ticket);
            }
            
            }catch(Exception e){
            System.out.println("Error");
            }
            try{
            //Gets data from file
            BufferedReader reader = new BufferedReader(new FileReader("employeedata.csv"));
            ArrayList<String> tableInfo = new ArrayList<>();
            String line;
            
            while ((line = reader.readLine()) != null){
                tableInfo.add(line);
            }
            reader.close();
            
            for(String rowInfo : tableInfo){
                String[] row = rowInfo.split(",");

                StaffDB staff = new StaffDB(row[0], row[1], row[2], row[3], row[4], row[5], 
                        Integer.valueOf(row[6]), Integer.valueOf(row[7]), Integer.valueOf(row[8]));
                employees.put(row[0], staff);

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Staff info not read correctly");
        }
            
        try{
            //Gets data from file
            BufferedReader reader = new BufferedReader(new FileReader("inventorydata.csv"));
            ArrayList<String> tableInfo = new ArrayList<>();
            String line;
            
            while ((line = reader.readLine()) != null){
                tableInfo.add(line);
            }
            reader.close();
            
            //Put data in table
            
            for(String rowInfo : tableInfo){
                String[] row = rowInfo.split(",");

                InventoryDB item = new InventoryDB(Integer.valueOf(row[4]), row[0], row[5], row[1], Integer.valueOf(row[2]), row[3]);
                items.put(Integer.valueOf(row[4]), item);
            }
        }catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_formWindowOpened

    private void TicketsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketsMenuButtonActionPerformed
        new TicketsMenu(tickets, manager).setVisible(true);
    }//GEN-LAST:event_TicketsMenuButtonActionPerformed

    private void inventoryMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryMenuButtonActionPerformed
        new Inventory(employees, items, manager).setVisible(true);
    }//GEN-LAST:event_inventoryMenuButtonActionPerformed

    private void customerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuButtonActionPerformed
        new CustomerFrame().setVisible(true);
    }//GEN-LAST:event_customerMenuButtonActionPerformed

    private void staffMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffMenuButtonActionPerformed
        new StaffFrame(employees).setVisible(true);
    }//GEN-LAST:event_staffMenuButtonActionPerformed

    private void storeInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeInfoButtonActionPerformed
        new UpdateStoreHoursPanel().setVisible(true);
    }//GEN-LAST:event_storeInfoButtonActionPerformed

    private void purchaseMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseMenuButtonActionPerformed
        new PurchaseGUI(items).setVisible(true);
    }//GEN-LAST:event_purchaseMenuButtonActionPerformed

    private void managerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerMenuButtonActionPerformed
        if(manager){
            new ManagerMenu(employees).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Invalid Credentials");
        }
    }//GEN-LAST:event_managerMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenuFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenuFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenuFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenuFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenuFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TicketsMenuButton;
    private javax.swing.JButton customerMenuButton;
    private javax.swing.JButton inventoryMenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton managerMenuButton;
    private javax.swing.JButton purchaseMenuButton;
    private javax.swing.JButton staffMenuButton;
    private javax.swing.JButton storeInfoButton;
    // End of variables declaration//GEN-END:variables
}
